[Mon, 21 Mar 2016 14:59:13] service.py [func:<module>] [line:88] ERROR: _init() missing 1 required positional argument: 'search_flag'
[Mon, 21 Mar 2016 14:59:13] service.py [func:<module>] [line:89] ERROR: data_service server starts failed.
[Mon, 21 Mar 2016 15:50:13] service.py [func:get] [line:66] ERROR: Exception:≤ªƒ‹Ω´xx◊™ªªŒ™int¿‡–Õ
[Mon, 21 Mar 2016 15:51:21] path_planning.py [func:schedule] [line:902] ERROR: dictionary update sequence element #0 has length 1; 2 is required
[Mon, 21 Mar 2016 15:51:21] path_planning.py [func:schedule] [line:903] ERROR: {'data': {'gre': {'verbal': '12', 'total': '300'}, 'ielts': {'total': '7'}, 'reletter': {'level': ['1', '2', '3']}, 'competition': {'level': '2'}, 'gpa': {'score': '3.2', 'school': '9'}, 'scholarship': {'level': '2'}, 'internship': {'recommendation': '2', 'duration': '5', 'level': '3'}, 'research': {'recommendation': '1', 'duration': '1', 'level': '1', 'achievement': '1'}, 'toefl': {'speaking': '12', 'total': '110'}}, 'target': '1', 'major': 'cs', 'grade': '1'}

[Mon, 21 Mar 2016 15:53:39] path_planning.py [func:schedule] [line:901] ERROR: name '_calculate_nodes_weight' is not defined
[Mon, 21 Mar 2016 15:53:39] path_planning.py [func:schedule] [line:902] ERROR: {'data': {'competition': {'level': '2'}, 'gre': {'total': '300', 'verbal': '12'}, 'internship': {'level': '3', 'duration': '5', 'recommendation': '2'}, 'research': {'recommendation': '1', 'level': '1', 'achievement': '1', 'duration': '1'}, 'gpa': {'score': '3.2', 'school': '9'}, 'ielts': {'total': '7'}, 'toefl': {'total': '110', 'speaking': '12'}, 'reletter': {'level': ['1', '2', '3']}, 'scholarship': {'level': '2'}}, 'major': 'cs', 'grade': '1', 'target': '1'}

[Mon, 21 Mar 2016 15:58:35] path_planning.py [func:schedule] [line:901] ERROR: ≤ªƒ‹Ω´ ¥Û∂˛ ◊™ªªŒ™int¿‡–Õ ˝æ›
[Mon, 21 Mar 2016 15:58:35] path_planning.py [func:schedule] [line:902] ERROR: {'data': {'competition': {'level': '2'}, 'gre': {'total': '300', 'verbal': '12'}, 'internship': {'level': '3', 'duration': '5', 'recommendation': '2'}, 'research': {'recommendation': '1', 'level': '1', 'achievement': '1', 'duration': '1'}, 'gpa': {'score': '3.2', 'school': '9'}, 'ielts': {'total': '7'}, 'toefl': {'total': '110', 'speaking': '12'}, 'reletter': {'level': ['1', '2', '3']}, 'scholarship': {'level': '2'}}, 'major': 'cs', 'grade': '¥Û∂˛', 'target': '1'}

[Mon, 21 Mar 2016 16:05:45] path_planning.py [func:schedule] [line:900] ERROR: ‰∏çËÉΩÂ∞Ü Â§ß‰∫å ËΩ¨Êç¢‰∏∫intÁ±ªÂûãÊï∞ÊçÆ
[Mon, 21 Mar 2016 16:05:45] path_planning.py [func:schedule] [line:901] ERROR: {'grade': 'Â§ß‰∫å', 'target': '1', 'major': 'cs', 'data': {'reletter': {'level': ['1', '2', '3']}, 'internship': {'recommendation': '2', 'level': '3', 'duration': '5'}, 'toefl': {'speaking': '12', 'total': '110'}, 'gpa': {'school': '9', 'score': '3.2'}, 'gre': {'verbal': '12', 'total': '300'}, 'ielts': {'total': '7'}, 'scholarship': {'level': '2'}, 'competition': {'level': '2'}, 'research': {'achievement': '1', 'recommendation': '1', 'level': '1', 'duration': '1'}}}

[Mon, 21 Mar 2016 16:07:29] service.py [func:get] [line:66] ERROR: Exception:local variable 'user_analysis' referenced before assignment
